### ISSUE TITLE
AttributeError: module 'jinja2.ext' has no attribute 'with_'

### ISSUE THREAD

**Issue by fr33tux** [recitale/recitale#12]
When running `recitale build` on Python 3.10 - Ubuntu 22.04 - Jinja2-3.1.2- Recitale 2.0.0a3:

```
Traceback (most recent call last):
  File "/home/jboursier/.local/bin/recitale", line 8, in <module>
    sys.exit(main())
  File "/home/jboursier/.local/lib/python3.10/site-packages/recitale/recitale.py", line 878, in main
    templates.add_extension("jinja2.ext.with_")
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 373, in add_extension
    self.extensions.update(load_extensions(self, [extension]))
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/usr/local/lib/python3.10/dist-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'with_'
```

It was working well with Python 3.9 with the same Recitale version, so I guess something broke with Jinja2 and Python3.10 - Have you been running into the same issue?
